server:
  port: 8081
spring:
  application:
    name: storage-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-t.whsshg.com:50538/xss_seata?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: ULG#-bZPWQUDI?M%:uT*L1zTQ3*E0Z
  cloud:
    alibaba:
      seata:
        tx-service-group: test_tx_group
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    cn.itcast: debug